### ISSUE TITLE
Issues with Context.Cache

### ISSUE THREAD

**Issue by KathleenDollard** [csharpfritz/WebFormsTest#22]
I have this in my test

```
        var cache = new System.Web.Caching.Cache();
        requestMock.SetupGet(r => r.Url).Returns(new Uri("http://theactualuri.com"));
        contextMock.SetupGet(r => r.Cache).Returns(cache);
```

and then get a NullRefException when I call this in my custom base page (under TestablePage) when firing the pages Load event 

```
            OrgView orgl = Context.Cache[url] as OrgView ;
```

The cache is present, the url is a Url (but not one that would actually be found) and the error occurs in the Context.Cache[url] call. 

Ideas?

**Comment by csharpfritz** [comment]
I would need to investigate on referencesource.micrososft.com to see what it is referencing.

Would you like to start a simple unit test fixture in WebFormsTest.Test to exercise exactly this to validate that Cache works?

**Comment by csharpfritz** [comment]
Reading into this further....  your test code doesn't assign the URL into the cache.

**Comment by csharpfritz** [comment]
You shouldn't create the Cache object in your own code, it is created and managed internally by HttpContext and attached to the HttpRuntime.  I've added a Cache property to the WebApplicationProxy that will always deliver the static Cache object that the WebApplication is maintaining.  

You do not need to have your page fully hydrated from WebApplicationProxy in order to use the Cache.  Try some code like this:

```
var cache = WebApplicationProxy.Cache;
cache.Insert("key", "value");
contextMock.SetupGet(r => r.Cache).Returns(cache);
```
