### ISSUE TITLE
Emulate entire page event lifecycle

### ISSUE THREAD

**Issue by csharpfritz** [csharpfritz/WebFormsTest#5]
Allow the shim to trigger the entire page lifecycle or part of the page with a single method call

**Comment by KathleenDollard** [comment]
This is important because without it, code could be added to an event that results in production breaks, without being caught in testing. 

The most common way this would happen is in a postback where Page_Load isn't doing anything and isn't triggered, tests pass, code is added to PageLoad and tests are no longer meaningful

While Page_Load is the most common, the same thing could occur with any life-cycle event.

**Comment by KathleenDollard** [comment]
After considering the auto wire-up question and the hydration issue

Perhaps naively, it seems either of the two options might work

1) hydrate the form sufficiently to have it fire events as though it was running in real mode
- Customizing test conditions (what button is enabled) may need to be done via a simulated request, which could be ugly without automated support. 

2) instantiate and having code (like in TestablePage) call the delegate implementations in the correct order
- Customizing test conditions could be done directly, but the evaluation of the proper event order might be tough

Not sure how ASPX/ASCX are treated with the Roslyn compiler.

**Comment by csharpfritz** [comment]
Precompilation with the WebApplicationProxy has completed significant progress on this one.  I want to break out the 'customize test conditions' item as a second issue and leave this issue as "Emulate entire lifecycle in proper order, stopping where directed"

However, that leads to an interesting idea.  If my unit test want to run the entire page lifecycle, do I connect Action methods from my unit test to event listeners for the Page?  Hmm... interesting possibility...
